/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ZhRouteImport } from './routes/zh'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as ManifestDotjsonRouteImport } from './routes/manifest[.]json'
import { Route as KoRouteImport } from './routes/ko'
import { Route as JaRouteImport } from './routes/ja'
import { Route as GeneratorRouteImport } from './routes/generator'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as EsRouteImport } from './routes/es'
import { Route as EnRouteImport } from './routes/en'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as BatchGeneratorRouteImport } from './routes/batch-generator'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ZhIndexRouteImport } from './routes/zh/index'
import { Route as ToolsIndexRouteImport } from './routes/tools/index'
import { Route as SettingsIndexRouteImport } from './routes/settings/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as BlogIndexRouteImport } from './routes/blog/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as ZhGalleryRouteImport } from './routes/zh/gallery'
import { Route as ZhBatchGeneratorRouteImport } from './routes/zh/batch-generator'
import { Route as ToolsSlugRouteImport } from './routes/tools/$slug'
import { Route as SettingsSecurityRouteImport } from './routes/settings/security'
import { Route as SettingsProfileRouteImport } from './routes/settings/profile'
import { Route as SettingsPaymentRouteImport } from './routes/settings/payment'
import { Route as SettingsNotificationsRouteImport } from './routes/settings/notifications'
import { Route as SettingsFilesRouteImport } from './routes/settings/files'
import { Route as SettingsBillingRouteImport } from './routes/settings/billing'
import { Route as SettingsApikeysRouteImport } from './routes/settings/apikeys'
import { Route as KoBatchGeneratorRouteImport } from './routes/ko/batch-generator'
import { Route as JaBatchGeneratorRouteImport } from './routes/ja/batch-generator'
import { Route as EsBatchGeneratorRouteImport } from './routes/es/batch-generator'
import { Route as BlogSlugRouteImport } from './routes/blog/$slug'
import { Route as AuthResetPasswordRouteImport } from './routes/auth/reset-password'
import { Route as AuthRegisterRouteImport } from './routes/auth/register'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AuthForgotPasswordRouteImport } from './routes/auth/forgot-password'
import { Route as AuthErrorRouteImport } from './routes/auth/error'
import { Route as ApiPingRouteImport } from './routes/api/ping'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as testsTestErrorRouteImport } from './routes/(tests)/test-error'
import { Route as testsTest404RouteImport } from './routes/(tests)/test-404'
import { Route as pagesWaitlistRouteImport } from './routes/(pages)/waitlist'
import { Route as pagesRoadmapRouteImport } from './routes/(pages)/roadmap'
import { Route as pagesPricingRouteImport } from './routes/(pages)/pricing'
import { Route as pagesContactRouteImport } from './routes/(pages)/contact'
import { Route as pagesChangelogRouteImport } from './routes/(pages)/changelog'
import { Route as pagesAiRouteImport } from './routes/(pages)/ai'
import { Route as pagesAboutRouteImport } from './routes/(pages)/about'
import { Route as legalsTermsRouteImport } from './routes/(legals)/terms'
import { Route as legalsPrivacyRouteImport } from './routes/(legals)/privacy'
import { Route as legalsCookieRouteImport } from './routes/(legals)/cookie'
import { Route as ZhToolsIndexRouteImport } from './routes/zh/tools/index'
import { Route as ZhToolsSlugRouteImport } from './routes/zh/tools/$slug'
import { Route as ApiWebhooksStripeRouteImport } from './routes/api/webhooks/stripe'
import { Route as ApiWebhooksCreemRouteImport } from './routes/api/webhooks/creem'
import { Route as ApiStorageFileRouteImport } from './routes/api/storage/file'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const ZhRoute = ZhRouteImport.update({
  id: '/zh',
  path: '/zh',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const ManifestDotjsonRoute = ManifestDotjsonRouteImport.update({
  id: '/manifest.json',
  path: '/manifest.json',
  getParentRoute: () => rootRouteImport,
} as any)
const KoRoute = KoRouteImport.update({
  id: '/ko',
  path: '/ko',
  getParentRoute: () => rootRouteImport,
} as any)
const JaRoute = JaRouteImport.update({
  id: '/ja',
  path: '/ja',
  getParentRoute: () => rootRouteImport,
} as any)
const GeneratorRoute = GeneratorRouteImport.update({
  id: '/generator',
  path: '/generator',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const EsRoute = EsRouteImport.update({
  id: '/es',
  path: '/es',
  getParentRoute: () => rootRouteImport,
} as any)
const EnRoute = EnRouteImport.update({
  id: '/en',
  path: '/en',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const BatchGeneratorRoute = BatchGeneratorRouteImport.update({
  id: '/batch-generator',
  path: '/batch-generator',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ZhIndexRoute = ZhIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ZhRoute,
} as any)
const ToolsIndexRoute = ToolsIndexRouteImport.update({
  id: '/tools/',
  path: '/tools/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SettingsRoute,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const ZhGalleryRoute = ZhGalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => ZhRoute,
} as any)
const ZhBatchGeneratorRoute = ZhBatchGeneratorRouteImport.update({
  id: '/batch-generator',
  path: '/batch-generator',
  getParentRoute: () => ZhRoute,
} as any)
const ToolsSlugRoute = ToolsSlugRouteImport.update({
  id: '/tools/$slug',
  path: '/tools/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsSecurityRoute = SettingsSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsProfileRoute = SettingsProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsPaymentRoute = SettingsPaymentRouteImport.update({
  id: '/payment',
  path: '/payment',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsNotificationsRoute = SettingsNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsFilesRoute = SettingsFilesRouteImport.update({
  id: '/files',
  path: '/files',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsBillingRoute = SettingsBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsApikeysRoute = SettingsApikeysRouteImport.update({
  id: '/apikeys',
  path: '/apikeys',
  getParentRoute: () => SettingsRoute,
} as any)
const KoBatchGeneratorRoute = KoBatchGeneratorRouteImport.update({
  id: '/batch-generator',
  path: '/batch-generator',
  getParentRoute: () => KoRoute,
} as any)
const JaBatchGeneratorRoute = JaBatchGeneratorRouteImport.update({
  id: '/batch-generator',
  path: '/batch-generator',
  getParentRoute: () => JaRoute,
} as any)
const EsBatchGeneratorRoute = EsBatchGeneratorRouteImport.update({
  id: '/batch-generator',
  path: '/batch-generator',
  getParentRoute: () => EsRoute,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => AuthRoute,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AuthRoute,
} as any)
const AuthErrorRoute = AuthErrorRouteImport.update({
  id: '/error',
  path: '/error',
  getParentRoute: () => AuthRoute,
} as any)
const ApiPingRoute = ApiPingRouteImport.update({
  id: '/api/ping',
  path: '/api/ping',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const testsTestErrorRoute = testsTestErrorRouteImport.update({
  id: '/(tests)/test-error',
  path: '/test-error',
  getParentRoute: () => rootRouteImport,
} as any)
const testsTest404Route = testsTest404RouteImport.update({
  id: '/(tests)/test-404',
  path: '/test-404',
  getParentRoute: () => rootRouteImport,
} as any)
const pagesWaitlistRoute = pagesWaitlistRouteImport.update({
  id: '/(pages)/waitlist',
  path: '/waitlist',
  getParentRoute: () => rootRouteImport,
} as any)
const pagesRoadmapRoute = pagesRoadmapRouteImport.update({
  id: '/(pages)/roadmap',
  path: '/roadmap',
  getParentRoute: () => rootRouteImport,
} as any)
const pagesPricingRoute = pagesPricingRouteImport.update({
  id: '/(pages)/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const pagesContactRoute = pagesContactRouteImport.update({
  id: '/(pages)/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const pagesChangelogRoute = pagesChangelogRouteImport.update({
  id: '/(pages)/changelog',
  path: '/changelog',
  getParentRoute: () => rootRouteImport,
} as any)
const pagesAiRoute = pagesAiRouteImport.update({
  id: '/(pages)/ai',
  path: '/ai',
  getParentRoute: () => rootRouteImport,
} as any)
const pagesAboutRoute = pagesAboutRouteImport.update({
  id: '/(pages)/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const legalsTermsRoute = legalsTermsRouteImport.update({
  id: '/(legals)/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const legalsPrivacyRoute = legalsPrivacyRouteImport.update({
  id: '/(legals)/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const legalsCookieRoute = legalsCookieRouteImport.update({
  id: '/(legals)/cookie',
  path: '/cookie',
  getParentRoute: () => rootRouteImport,
} as any)
const ZhToolsIndexRoute = ZhToolsIndexRouteImport.update({
  id: '/tools/',
  path: '/tools/',
  getParentRoute: () => ZhRoute,
} as any)
const ZhToolsSlugRoute = ZhToolsSlugRouteImport.update({
  id: '/tools/$slug',
  path: '/tools/$slug',
  getParentRoute: () => ZhRoute,
} as any)
const ApiWebhooksStripeRoute = ApiWebhooksStripeRouteImport.update({
  id: '/api/webhooks/stripe',
  path: '/api/webhooks/stripe',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWebhooksCreemRoute = ApiWebhooksCreemRouteImport.update({
  id: '/api/webhooks/creem',
  path: '/api/webhooks/creem',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStorageFileRoute = ApiStorageFileRouteImport.update({
  id: '/api/storage/file',
  path: '/api/storage/file',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/batch-generator': typeof BatchGeneratorRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/en': typeof EnRoute
  '/es': typeof EsRouteWithChildren
  '/gallery': typeof GalleryRoute
  '/generator': typeof GeneratorRoute
  '/ja': typeof JaRouteWithChildren
  '/ko': typeof KoRouteWithChildren
  '/manifest.json': typeof ManifestDotjsonRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/settings': typeof SettingsRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/zh': typeof ZhRouteWithChildren
  '/cookie': typeof legalsCookieRoute
  '/privacy': typeof legalsPrivacyRoute
  '/terms': typeof legalsTermsRoute
  '/about': typeof pagesAboutRoute
  '/ai': typeof pagesAiRoute
  '/changelog': typeof pagesChangelogRoute
  '/contact': typeof pagesContactRoute
  '/pricing': typeof pagesPricingRoute
  '/roadmap': typeof pagesRoadmapRoute
  '/waitlist': typeof pagesWaitlistRoute
  '/test-404': typeof testsTest404Route
  '/test-error': typeof testsTestErrorRoute
  '/admin/users': typeof AdminUsersRoute
  '/api/ping': typeof ApiPingRoute
  '/auth/error': typeof AuthErrorRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/es/batch-generator': typeof EsBatchGeneratorRoute
  '/ja/batch-generator': typeof JaBatchGeneratorRoute
  '/ko/batch-generator': typeof KoBatchGeneratorRoute
  '/settings/apikeys': typeof SettingsApikeysRoute
  '/settings/billing': typeof SettingsBillingRoute
  '/settings/files': typeof SettingsFilesRoute
  '/settings/notifications': typeof SettingsNotificationsRoute
  '/settings/payment': typeof SettingsPaymentRoute
  '/settings/profile': typeof SettingsProfileRoute
  '/settings/security': typeof SettingsSecurityRoute
  '/tools/$slug': typeof ToolsSlugRoute
  '/zh/batch-generator': typeof ZhBatchGeneratorRoute
  '/zh/gallery': typeof ZhGalleryRoute
  '/admin/': typeof AdminIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/tools/': typeof ToolsIndexRoute
  '/zh/': typeof ZhIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/storage/file': typeof ApiStorageFileRoute
  '/api/webhooks/creem': typeof ApiWebhooksCreemRoute
  '/api/webhooks/stripe': typeof ApiWebhooksStripeRoute
  '/zh/tools/$slug': typeof ZhToolsSlugRoute
  '/zh/tools/': typeof ZhToolsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/batch-generator': typeof BatchGeneratorRoute
  '/en': typeof EnRoute
  '/es': typeof EsRouteWithChildren
  '/gallery': typeof GalleryRoute
  '/generator': typeof GeneratorRoute
  '/ja': typeof JaRouteWithChildren
  '/ko': typeof KoRouteWithChildren
  '/manifest.json': typeof ManifestDotjsonRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/cookie': typeof legalsCookieRoute
  '/privacy': typeof legalsPrivacyRoute
  '/terms': typeof legalsTermsRoute
  '/about': typeof pagesAboutRoute
  '/ai': typeof pagesAiRoute
  '/changelog': typeof pagesChangelogRoute
  '/contact': typeof pagesContactRoute
  '/pricing': typeof pagesPricingRoute
  '/roadmap': typeof pagesRoadmapRoute
  '/waitlist': typeof pagesWaitlistRoute
  '/test-404': typeof testsTest404Route
  '/test-error': typeof testsTestErrorRoute
  '/admin/users': typeof AdminUsersRoute
  '/api/ping': typeof ApiPingRoute
  '/auth/error': typeof AuthErrorRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/es/batch-generator': typeof EsBatchGeneratorRoute
  '/ja/batch-generator': typeof JaBatchGeneratorRoute
  '/ko/batch-generator': typeof KoBatchGeneratorRoute
  '/settings/apikeys': typeof SettingsApikeysRoute
  '/settings/billing': typeof SettingsBillingRoute
  '/settings/files': typeof SettingsFilesRoute
  '/settings/notifications': typeof SettingsNotificationsRoute
  '/settings/payment': typeof SettingsPaymentRoute
  '/settings/profile': typeof SettingsProfileRoute
  '/settings/security': typeof SettingsSecurityRoute
  '/tools/$slug': typeof ToolsSlugRoute
  '/zh/batch-generator': typeof ZhBatchGeneratorRoute
  '/zh/gallery': typeof ZhGalleryRoute
  '/admin': typeof AdminIndexRoute
  '/blog': typeof BlogIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/tools': typeof ToolsIndexRoute
  '/zh': typeof ZhIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/storage/file': typeof ApiStorageFileRoute
  '/api/webhooks/creem': typeof ApiWebhooksCreemRoute
  '/api/webhooks/stripe': typeof ApiWebhooksStripeRoute
  '/zh/tools/$slug': typeof ZhToolsSlugRoute
  '/zh/tools': typeof ZhToolsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/batch-generator': typeof BatchGeneratorRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/en': typeof EnRoute
  '/es': typeof EsRouteWithChildren
  '/gallery': typeof GalleryRoute
  '/generator': typeof GeneratorRoute
  '/ja': typeof JaRouteWithChildren
  '/ko': typeof KoRouteWithChildren
  '/manifest.json': typeof ManifestDotjsonRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/settings': typeof SettingsRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/zh': typeof ZhRouteWithChildren
  '/(legals)/cookie': typeof legalsCookieRoute
  '/(legals)/privacy': typeof legalsPrivacyRoute
  '/(legals)/terms': typeof legalsTermsRoute
  '/(pages)/about': typeof pagesAboutRoute
  '/(pages)/ai': typeof pagesAiRoute
  '/(pages)/changelog': typeof pagesChangelogRoute
  '/(pages)/contact': typeof pagesContactRoute
  '/(pages)/pricing': typeof pagesPricingRoute
  '/(pages)/roadmap': typeof pagesRoadmapRoute
  '/(pages)/waitlist': typeof pagesWaitlistRoute
  '/(tests)/test-404': typeof testsTest404Route
  '/(tests)/test-error': typeof testsTestErrorRoute
  '/admin/users': typeof AdminUsersRoute
  '/api/ping': typeof ApiPingRoute
  '/auth/error': typeof AuthErrorRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/es/batch-generator': typeof EsBatchGeneratorRoute
  '/ja/batch-generator': typeof JaBatchGeneratorRoute
  '/ko/batch-generator': typeof KoBatchGeneratorRoute
  '/settings/apikeys': typeof SettingsApikeysRoute
  '/settings/billing': typeof SettingsBillingRoute
  '/settings/files': typeof SettingsFilesRoute
  '/settings/notifications': typeof SettingsNotificationsRoute
  '/settings/payment': typeof SettingsPaymentRoute
  '/settings/profile': typeof SettingsProfileRoute
  '/settings/security': typeof SettingsSecurityRoute
  '/tools/$slug': typeof ToolsSlugRoute
  '/zh/batch-generator': typeof ZhBatchGeneratorRoute
  '/zh/gallery': typeof ZhGalleryRoute
  '/admin/': typeof AdminIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/tools/': typeof ToolsIndexRoute
  '/zh/': typeof ZhIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/storage/file': typeof ApiStorageFileRoute
  '/api/webhooks/creem': typeof ApiWebhooksCreemRoute
  '/api/webhooks/stripe': typeof ApiWebhooksStripeRoute
  '/zh/tools/$slug': typeof ZhToolsSlugRoute
  '/zh/tools/': typeof ZhToolsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/batch-generator'
    | '/dashboard'
    | '/en'
    | '/es'
    | '/gallery'
    | '/generator'
    | '/ja'
    | '/ko'
    | '/manifest.json'
    | '/robots.txt'
    | '/settings'
    | '/sitemap.xml'
    | '/zh'
    | '/cookie'
    | '/privacy'
    | '/terms'
    | '/about'
    | '/ai'
    | '/changelog'
    | '/contact'
    | '/pricing'
    | '/roadmap'
    | '/waitlist'
    | '/test-404'
    | '/test-error'
    | '/admin/users'
    | '/api/ping'
    | '/auth/error'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/register'
    | '/auth/reset-password'
    | '/blog/$slug'
    | '/es/batch-generator'
    | '/ja/batch-generator'
    | '/ko/batch-generator'
    | '/settings/apikeys'
    | '/settings/billing'
    | '/settings/files'
    | '/settings/notifications'
    | '/settings/payment'
    | '/settings/profile'
    | '/settings/security'
    | '/tools/$slug'
    | '/zh/batch-generator'
    | '/zh/gallery'
    | '/admin/'
    | '/blog/'
    | '/dashboard/'
    | '/settings/'
    | '/tools/'
    | '/zh/'
    | '/api/auth/$'
    | '/api/storage/file'
    | '/api/webhooks/creem'
    | '/api/webhooks/stripe'
    | '/zh/tools/$slug'
    | '/zh/tools/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/batch-generator'
    | '/en'
    | '/es'
    | '/gallery'
    | '/generator'
    | '/ja'
    | '/ko'
    | '/manifest.json'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/cookie'
    | '/privacy'
    | '/terms'
    | '/about'
    | '/ai'
    | '/changelog'
    | '/contact'
    | '/pricing'
    | '/roadmap'
    | '/waitlist'
    | '/test-404'
    | '/test-error'
    | '/admin/users'
    | '/api/ping'
    | '/auth/error'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/register'
    | '/auth/reset-password'
    | '/blog/$slug'
    | '/es/batch-generator'
    | '/ja/batch-generator'
    | '/ko/batch-generator'
    | '/settings/apikeys'
    | '/settings/billing'
    | '/settings/files'
    | '/settings/notifications'
    | '/settings/payment'
    | '/settings/profile'
    | '/settings/security'
    | '/tools/$slug'
    | '/zh/batch-generator'
    | '/zh/gallery'
    | '/admin'
    | '/blog'
    | '/dashboard'
    | '/settings'
    | '/tools'
    | '/zh'
    | '/api/auth/$'
    | '/api/storage/file'
    | '/api/webhooks/creem'
    | '/api/webhooks/stripe'
    | '/zh/tools/$slug'
    | '/zh/tools'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/batch-generator'
    | '/dashboard'
    | '/en'
    | '/es'
    | '/gallery'
    | '/generator'
    | '/ja'
    | '/ko'
    | '/manifest.json'
    | '/robots.txt'
    | '/settings'
    | '/sitemap.xml'
    | '/zh'
    | '/(legals)/cookie'
    | '/(legals)/privacy'
    | '/(legals)/terms'
    | '/(pages)/about'
    | '/(pages)/ai'
    | '/(pages)/changelog'
    | '/(pages)/contact'
    | '/(pages)/pricing'
    | '/(pages)/roadmap'
    | '/(pages)/waitlist'
    | '/(tests)/test-404'
    | '/(tests)/test-error'
    | '/admin/users'
    | '/api/ping'
    | '/auth/error'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/register'
    | '/auth/reset-password'
    | '/blog/$slug'
    | '/es/batch-generator'
    | '/ja/batch-generator'
    | '/ko/batch-generator'
    | '/settings/apikeys'
    | '/settings/billing'
    | '/settings/files'
    | '/settings/notifications'
    | '/settings/payment'
    | '/settings/profile'
    | '/settings/security'
    | '/tools/$slug'
    | '/zh/batch-generator'
    | '/zh/gallery'
    | '/admin/'
    | '/blog/'
    | '/dashboard/'
    | '/settings/'
    | '/tools/'
    | '/zh/'
    | '/api/auth/$'
    | '/api/storage/file'
    | '/api/webhooks/creem'
    | '/api/webhooks/stripe'
    | '/zh/tools/$slug'
    | '/zh/tools/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  BatchGeneratorRoute: typeof BatchGeneratorRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  EnRoute: typeof EnRoute
  EsRoute: typeof EsRouteWithChildren
  GalleryRoute: typeof GalleryRoute
  GeneratorRoute: typeof GeneratorRoute
  JaRoute: typeof JaRouteWithChildren
  KoRoute: typeof KoRouteWithChildren
  ManifestDotjsonRoute: typeof ManifestDotjsonRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SettingsRoute: typeof SettingsRouteWithChildren
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ZhRoute: typeof ZhRouteWithChildren
  legalsCookieRoute: typeof legalsCookieRoute
  legalsPrivacyRoute: typeof legalsPrivacyRoute
  legalsTermsRoute: typeof legalsTermsRoute
  pagesAboutRoute: typeof pagesAboutRoute
  pagesAiRoute: typeof pagesAiRoute
  pagesChangelogRoute: typeof pagesChangelogRoute
  pagesContactRoute: typeof pagesContactRoute
  pagesPricingRoute: typeof pagesPricingRoute
  pagesRoadmapRoute: typeof pagesRoadmapRoute
  pagesWaitlistRoute: typeof pagesWaitlistRoute
  testsTest404Route: typeof testsTest404Route
  testsTestErrorRoute: typeof testsTestErrorRoute
  ApiPingRoute: typeof ApiPingRoute
  BlogSlugRoute: typeof BlogSlugRoute
  ToolsSlugRoute: typeof ToolsSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
  ToolsIndexRoute: typeof ToolsIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiStorageFileRoute: typeof ApiStorageFileRoute
  ApiWebhooksCreemRoute: typeof ApiWebhooksCreemRoute
  ApiWebhooksStripeRoute: typeof ApiWebhooksStripeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/zh': {
      id: '/zh'
      path: '/zh'
      fullPath: '/zh'
      preLoaderRoute: typeof ZhRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manifest.json': {
      id: '/manifest.json'
      path: '/manifest.json'
      fullPath: '/manifest.json'
      preLoaderRoute: typeof ManifestDotjsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ko': {
      id: '/ko'
      path: '/ko'
      fullPath: '/ko'
      preLoaderRoute: typeof KoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ja': {
      id: '/ja'
      path: '/ja'
      fullPath: '/ja'
      preLoaderRoute: typeof JaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/generator': {
      id: '/generator'
      path: '/generator'
      fullPath: '/generator'
      preLoaderRoute: typeof GeneratorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/es': {
      id: '/es'
      path: '/es'
      fullPath: '/es'
      preLoaderRoute: typeof EsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en': {
      id: '/en'
      path: '/en'
      fullPath: '/en'
      preLoaderRoute: typeof EnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/batch-generator': {
      id: '/batch-generator'
      path: '/batch-generator'
      fullPath: '/batch-generator'
      preLoaderRoute: typeof BatchGeneratorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/zh/': {
      id: '/zh/'
      path: '/'
      fullPath: '/zh/'
      preLoaderRoute: typeof ZhIndexRouteImport
      parentRoute: typeof ZhRoute
    }
    '/tools/': {
      id: '/tools/'
      path: '/tools'
      fullPath: '/tools/'
      preLoaderRoute: typeof ToolsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/zh/gallery': {
      id: '/zh/gallery'
      path: '/gallery'
      fullPath: '/zh/gallery'
      preLoaderRoute: typeof ZhGalleryRouteImport
      parentRoute: typeof ZhRoute
    }
    '/zh/batch-generator': {
      id: '/zh/batch-generator'
      path: '/batch-generator'
      fullPath: '/zh/batch-generator'
      preLoaderRoute: typeof ZhBatchGeneratorRouteImport
      parentRoute: typeof ZhRoute
    }
    '/tools/$slug': {
      id: '/tools/$slug'
      path: '/tools/$slug'
      fullPath: '/tools/$slug'
      preLoaderRoute: typeof ToolsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/security': {
      id: '/settings/security'
      path: '/security'
      fullPath: '/settings/security'
      preLoaderRoute: typeof SettingsSecurityRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/profile': {
      id: '/settings/profile'
      path: '/profile'
      fullPath: '/settings/profile'
      preLoaderRoute: typeof SettingsProfileRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/payment': {
      id: '/settings/payment'
      path: '/payment'
      fullPath: '/settings/payment'
      preLoaderRoute: typeof SettingsPaymentRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/notifications': {
      id: '/settings/notifications'
      path: '/notifications'
      fullPath: '/settings/notifications'
      preLoaderRoute: typeof SettingsNotificationsRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/files': {
      id: '/settings/files'
      path: '/files'
      fullPath: '/settings/files'
      preLoaderRoute: typeof SettingsFilesRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/billing': {
      id: '/settings/billing'
      path: '/billing'
      fullPath: '/settings/billing'
      preLoaderRoute: typeof SettingsBillingRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/apikeys': {
      id: '/settings/apikeys'
      path: '/apikeys'
      fullPath: '/settings/apikeys'
      preLoaderRoute: typeof SettingsApikeysRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/ko/batch-generator': {
      id: '/ko/batch-generator'
      path: '/batch-generator'
      fullPath: '/ko/batch-generator'
      preLoaderRoute: typeof KoBatchGeneratorRouteImport
      parentRoute: typeof KoRoute
    }
    '/ja/batch-generator': {
      id: '/ja/batch-generator'
      path: '/batch-generator'
      fullPath: '/ja/batch-generator'
      preLoaderRoute: typeof JaBatchGeneratorRouteImport
      parentRoute: typeof JaRoute
    }
    '/es/batch-generator': {
      id: '/es/batch-generator'
      path: '/batch-generator'
      fullPath: '/es/batch-generator'
      preLoaderRoute: typeof EsBatchGeneratorRouteImport
      parentRoute: typeof EsRoute
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/reset-password': {
      id: '/auth/reset-password'
      path: '/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/forgot-password': {
      id: '/auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/error': {
      id: '/auth/error'
      path: '/error'
      fullPath: '/auth/error'
      preLoaderRoute: typeof AuthErrorRouteImport
      parentRoute: typeof AuthRoute
    }
    '/api/ping': {
      id: '/api/ping'
      path: '/api/ping'
      fullPath: '/api/ping'
      preLoaderRoute: typeof ApiPingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/(tests)/test-error': {
      id: '/(tests)/test-error'
      path: '/test-error'
      fullPath: '/test-error'
      preLoaderRoute: typeof testsTestErrorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(tests)/test-404': {
      id: '/(tests)/test-404'
      path: '/test-404'
      fullPath: '/test-404'
      preLoaderRoute: typeof testsTest404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(pages)/waitlist': {
      id: '/(pages)/waitlist'
      path: '/waitlist'
      fullPath: '/waitlist'
      preLoaderRoute: typeof pagesWaitlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(pages)/roadmap': {
      id: '/(pages)/roadmap'
      path: '/roadmap'
      fullPath: '/roadmap'
      preLoaderRoute: typeof pagesRoadmapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(pages)/pricing': {
      id: '/(pages)/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof pagesPricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(pages)/contact': {
      id: '/(pages)/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof pagesContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(pages)/changelog': {
      id: '/(pages)/changelog'
      path: '/changelog'
      fullPath: '/changelog'
      preLoaderRoute: typeof pagesChangelogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(pages)/ai': {
      id: '/(pages)/ai'
      path: '/ai'
      fullPath: '/ai'
      preLoaderRoute: typeof pagesAiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(pages)/about': {
      id: '/(pages)/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof pagesAboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(legals)/terms': {
      id: '/(legals)/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof legalsTermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(legals)/privacy': {
      id: '/(legals)/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof legalsPrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(legals)/cookie': {
      id: '/(legals)/cookie'
      path: '/cookie'
      fullPath: '/cookie'
      preLoaderRoute: typeof legalsCookieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/zh/tools/': {
      id: '/zh/tools/'
      path: '/tools'
      fullPath: '/zh/tools/'
      preLoaderRoute: typeof ZhToolsIndexRouteImport
      parentRoute: typeof ZhRoute
    }
    '/zh/tools/$slug': {
      id: '/zh/tools/$slug'
      path: '/tools/$slug'
      fullPath: '/zh/tools/$slug'
      preLoaderRoute: typeof ZhToolsSlugRouteImport
      parentRoute: typeof ZhRoute
    }
    '/api/webhooks/stripe': {
      id: '/api/webhooks/stripe'
      path: '/api/webhooks/stripe'
      fullPath: '/api/webhooks/stripe'
      preLoaderRoute: typeof ApiWebhooksStripeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/webhooks/creem': {
      id: '/api/webhooks/creem'
      path: '/api/webhooks/creem'
      fullPath: '/api/webhooks/creem'
      preLoaderRoute: typeof ApiWebhooksCreemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/storage/file': {
      id: '/api/storage/file'
      path: '/api/storage/file'
      fullPath: '/api/storage/file'
      preLoaderRoute: typeof ApiStorageFileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AuthRouteChildren {
  AuthErrorRoute: typeof AuthErrorRoute
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthErrorRoute: AuthErrorRoute,
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface DashboardRouteChildren {
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

interface EsRouteChildren {
  EsBatchGeneratorRoute: typeof EsBatchGeneratorRoute
}

const EsRouteChildren: EsRouteChildren = {
  EsBatchGeneratorRoute: EsBatchGeneratorRoute,
}

const EsRouteWithChildren = EsRoute._addFileChildren(EsRouteChildren)

interface JaRouteChildren {
  JaBatchGeneratorRoute: typeof JaBatchGeneratorRoute
}

const JaRouteChildren: JaRouteChildren = {
  JaBatchGeneratorRoute: JaBatchGeneratorRoute,
}

const JaRouteWithChildren = JaRoute._addFileChildren(JaRouteChildren)

interface KoRouteChildren {
  KoBatchGeneratorRoute: typeof KoBatchGeneratorRoute
}

const KoRouteChildren: KoRouteChildren = {
  KoBatchGeneratorRoute: KoBatchGeneratorRoute,
}

const KoRouteWithChildren = KoRoute._addFileChildren(KoRouteChildren)

interface SettingsRouteChildren {
  SettingsApikeysRoute: typeof SettingsApikeysRoute
  SettingsBillingRoute: typeof SettingsBillingRoute
  SettingsFilesRoute: typeof SettingsFilesRoute
  SettingsNotificationsRoute: typeof SettingsNotificationsRoute
  SettingsPaymentRoute: typeof SettingsPaymentRoute
  SettingsProfileRoute: typeof SettingsProfileRoute
  SettingsSecurityRoute: typeof SettingsSecurityRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
}

const SettingsRouteChildren: SettingsRouteChildren = {
  SettingsApikeysRoute: SettingsApikeysRoute,
  SettingsBillingRoute: SettingsBillingRoute,
  SettingsFilesRoute: SettingsFilesRoute,
  SettingsNotificationsRoute: SettingsNotificationsRoute,
  SettingsPaymentRoute: SettingsPaymentRoute,
  SettingsProfileRoute: SettingsProfileRoute,
  SettingsSecurityRoute: SettingsSecurityRoute,
  SettingsIndexRoute: SettingsIndexRoute,
}

const SettingsRouteWithChildren = SettingsRoute._addFileChildren(
  SettingsRouteChildren,
)

interface ZhRouteChildren {
  ZhBatchGeneratorRoute: typeof ZhBatchGeneratorRoute
  ZhGalleryRoute: typeof ZhGalleryRoute
  ZhIndexRoute: typeof ZhIndexRoute
  ZhToolsSlugRoute: typeof ZhToolsSlugRoute
  ZhToolsIndexRoute: typeof ZhToolsIndexRoute
}

const ZhRouteChildren: ZhRouteChildren = {
  ZhBatchGeneratorRoute: ZhBatchGeneratorRoute,
  ZhGalleryRoute: ZhGalleryRoute,
  ZhIndexRoute: ZhIndexRoute,
  ZhToolsSlugRoute: ZhToolsSlugRoute,
  ZhToolsIndexRoute: ZhToolsIndexRoute,
}

const ZhRouteWithChildren = ZhRoute._addFileChildren(ZhRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  BatchGeneratorRoute: BatchGeneratorRoute,
  DashboardRoute: DashboardRouteWithChildren,
  EnRoute: EnRoute,
  EsRoute: EsRouteWithChildren,
  GalleryRoute: GalleryRoute,
  GeneratorRoute: GeneratorRoute,
  JaRoute: JaRouteWithChildren,
  KoRoute: KoRouteWithChildren,
  ManifestDotjsonRoute: ManifestDotjsonRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SettingsRoute: SettingsRouteWithChildren,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ZhRoute: ZhRouteWithChildren,
  legalsCookieRoute: legalsCookieRoute,
  legalsPrivacyRoute: legalsPrivacyRoute,
  legalsTermsRoute: legalsTermsRoute,
  pagesAboutRoute: pagesAboutRoute,
  pagesAiRoute: pagesAiRoute,
  pagesChangelogRoute: pagesChangelogRoute,
  pagesContactRoute: pagesContactRoute,
  pagesPricingRoute: pagesPricingRoute,
  pagesRoadmapRoute: pagesRoadmapRoute,
  pagesWaitlistRoute: pagesWaitlistRoute,
  testsTest404Route: testsTest404Route,
  testsTestErrorRoute: testsTestErrorRoute,
  ApiPingRoute: ApiPingRoute,
  BlogSlugRoute: BlogSlugRoute,
  ToolsSlugRoute: ToolsSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
  ToolsIndexRoute: ToolsIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiStorageFileRoute: ApiStorageFileRoute,
  ApiWebhooksCreemRoute: ApiWebhooksCreemRoute,
  ApiWebhooksStripeRoute: ApiWebhooksStripeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.tsx'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
